<section class="category">
  <div class="container">
    <div class="row">
      <h3>Категории</h3>
      <div class="col-xs-6">
        <div class="category-col"><a href="vse-dla-detei/"><span class="fa fa-child"></span><span>Детский мир</span></a><a href="nedvijimost/"><span class="fa fa-key"></span><span>Недвижимость</span></a><a href="auto/"><span class="fa fa-car"></span><span>Транспорт</span></a><a href="rabota/"><span class="fa fa-briefcase"></span><span>Работа</span></a><a href="animals/"><span class="fa fa-paw"></span><span>Животные</span></a><a href="dom-i-sad/"><span class="fa fa-home"></span>
            <sapn>Дом и сад</sapn></a></div>
      </div>
      <div class="col-xs-6">
        <div class="category-col"><a href="electronika/"><span class="fa fa-television"></span><span>Электроника</span></a><a href="mebel/"><span class="fa fa-list-alt"></span><span>Услуги</span></a><a href="odejda/"><span class="fa fa-black-tie"></span><span>Одежда</span></a><a href="hobbi-i-otdyh/"><span class="fa fa-sun-o"></span><span>Хобби и отдых</span></a><a href="business/"><span class="fa fa-building"></span><span>Бизнес</span></a><a href="znakomstva/"><span class="fa fa-heart"></span><span>Знакомства</span></a></div>
      </div>
    </div>
  </div>
</section>
<section class="region">
  <div class="container">
    <div class="row">
      <h3>Выберете регион</h3>
    </div>
    <div class="row">
      <div class="region-list">
        <ul>
          <li><a href='/kievskaya_obl/'>Киев</a></li>
          <li><a href='/chernigovskaya_obl/'>Чернигов</a></li>
          <li><a href='/sumskaya_obl/'>Сумы</a></li>
          <li><a href='/harkovskaya_obl/'>Харьков</a></li>
          <li><a href='/luganskaya_obl/'>Луганск</a></li>
          <li><a href='/donetskaya_obl/'>Донецк</a></li>
          <li><a href='/zaporojskaya_obl/'>Запорожье</a></li>
          <li><a href='/dnepropetrovskaya_obl/'>Днепропетровск</a></li>
          <li><a href='/poltavskaya_obl/'>Полтава</a></li>
          <li><a href='/hersonskaya_obl/'>Херсон</a></li>
          <li><a href='/odesskaya_obl/'>Одесса</a></li>
          <li><a href='/nikolaevskaya_obl/'>Николаев</a></li>
          <li><a href='/kirovogradskaya_obl/'>Кировоград</a></li>
          <li><a href='/cherkasskaya_obl/'>Черкассы</a></li>
          <li><a href='/vinnitskaya_obl/'>Винница</a></li>
          <li><a href='/jitomirskaya_obl/'>Житомир</a></li>
          <li><a href='/rovnenskaya_obl/'>Ровно</a></li>
          <li><a href='/volyinskaya_obl/'>Луцк</a></li>
          <li><a href='/lvovskaya_obl/'>Львов</a></li>
          <li><a href='/zakarpatskaya_obl/'>Ужгород</a></li>
          <li><a href='/ivano-frankovskaya_obl/'>Ивано-Франковск</a></li>
          <li><a href='/chernovitskaya_obl/'>Черновцы</a></li>
          <li><a href='/ternopolskaya_obl/'>Тернополь</a></li>
          <li><a href='/hmelnitskaya_obl/'>Хмельницкий</a></li>
          <li><a href='/ar_kryim/'>АР Крым</a></li>
        </ul>
      </div>
    </div>
  </div>
</section>
